### PR TITLE
Replace deprecated canvas-prebuilt by canvas

### LINKED ISSUE #94: Remove canvas-prebuilt from devDependencies?
### Description

- When running `npm install` on the master branch, I get a 404 error because the tar.gz of `canvas-prebuilt` is not found for `node-v67-linux-x64`

- According to https://github.com/node-gfx/node-canvas-prebuilt
> the canvas-prebuilt package is deprecated. As of version 2, canvas itself bundles prebuilt versions from this repo. 

- Finally, I coudn't find any use of `canvas-prebuilt` or `canvas`. Is it actually used?

### Steps to reproduce

1. `npm install`
2. :boom:

### PR DESCRIPTION
**Pull request by michalochman**
Fixes #94

@matthieu-foucault also added the `cross-env` dev dependency, allowing to run build scripts on windows

### CODE REVIEW

**Comment by michalochman** [comment]
@matthieu-foucault looks like tests do not pass when you remove `canvas-prebuilt` from dependencies.

```TypeError: Cannot set property 'fillStyle' of null```

**Comment by michalochman** [comment]
Looks like this is because the current `jest` version is using `jsdom` that can not work with `canvas@2` yet.

**Comment by matthieu-foucault** [comment]
The tests for this PR did pass on CircleCI though 🤔

**Comment by michalochman** [comment]
That's because `canvas-prebuilt` is still in `devDependencies` ;)

I have solution to it thought through custom jest environment thought so I'll update this PR shortly.

**Comment by matthieu-foucault** [comment]
> That's because `canvas-prebuilt` is still in `devDependencies` ;)

🤦‍♂️

**Pull request merged**
