### PR TITLE
Support Pixi 7.1 events

### PR DESCRIPTION
**Pull request by zOadT**
Utilizes the work in https://github.com/pixijs/pixijs/pull/8876 to support event handler props for Pixi.js >= 7.1

Note: Pixi.js 7.1 isn't released yet and I also have to test the typings for Pixi < 7

### CODE REVIEW

**Comment by zOadT** [comment]
Hey! Pixi.js 7.1 got released yesterday. I tested this branch with pixi.js 7.1 and pixi.js 6.5.1 and it seems to work fine for both of them.

I found another issue with pixi.js 7.1 (unrelated to this PR) though. But I would open an issue for that and handle that in another PR if that's ok.

**Comment by michalochman** [comment]
Hi @zOadT, please do!

**Comment by zOadT** [comment]
Hello @michalochman, the issue I meant is #311. I want to handle that separately (because it is unrelated) but actually still wanted to get this PR merged 😅 (of course only if you don't have any issues with this PR)

**Comment by michalochman** [comment]
Sorry @zOadT! I misunderstood and thought your changes are not needed after fix in PixiJS 7.1.

**Review by michalochman — APPROVED** [review]

**Comment by michalochman** [comment]
Now I remember that they have prepended event props with `on`. Looks good, thanks for your contribution.

**Comment by zOadT** [comment]
No problem, thank you! 🙂

**Comment by michalochman** [comment]
Released in `react-pixi-fiber@1.0.5` 🎉

**Comment by michalochman** [comment]
Released in `react-pixi-fiber@1.0.6` 🎉

**Pull request merged**
