### PR TITLE
Add unstable_batchedUpdates API

### LINKED ISSUE #88: batchedUpdates without ReactDOM
### Description
HI!
`ReactDOM` has a `unstable_batchedUpdates` API to batch `setState` out of React context.
In `react-pixi-fiber`, if the React Pixi Fiber renderer is exported, I can get the `batchedUpdates` from it's instance, But seems it's not.( I think React Pixi Fiber renderer should be the internal. 
So can expose the `batchedUpdates` API? But it's a unstable API, maybe someday it'll be implemented and removed.
Any advise to do this?

### PR DESCRIPTION
**Pull request by liajoy**
Fixes #88 
Is `unstable_` prefix necessary?

### CODE REVIEW

**Comment by michalochman** [comment]
@liajoy looks good! Yeah, I'd keep the `unstable_` prefix to be consistent with `ReactDOM`. Would you be able to show a practical example of usage with PixiJS?

**Comment by michalochman** [comment]
@liajoy can you please [allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)? I'd like to push some changes to the example you prepared in this PR before I can merge.

**Comment by liajoy** [comment]
@michalochman seems 'allow edits from maintainers' is on.

**Comment by michalochman** [comment]
@liajoy are you ok with the changes I made?

**Comment by liajoy** [comment]
@michalochman totally agree! sorry for forgetting to lint code.

**Pull request merged**
